#Â Tasks required to have Koha QA Tools working for {{ user }}
- name: Koha QA tools | Packaged dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libfile-chdir-perl
    - libgit-repository-perl
    - liblist-compare-perl
    - libmoo-perl
    - libperl-critic-perl
    - libtest-perl-critic-perl
    - libtest-perl-critic-progressive-perl
    - libsmart-comments-perl
    - libdatetimex-easy-perl
    - libtest-differences-perl
    - libdbd-sqlite2-perl
    - codespell
    - libdbix-class-timestamp-perl
    - libmodule-install-perl
  become: yes

- name: Koha QA tools | CPAN dependencies
  become: yes
  cpanm:
    name: "{{ item }}"
    mirror: "{{ cpan_mirror }}"
  with_items:
    - DBD::SQLite
    - HTTPD::Bench::ApacheBench
    - MooseX::Attribute::ENV
    - Test::DBIx::Class
  retries: 5
  delay: 1

- name: Koha QA tools | Clone repository
  git:
    repo: "{{ koha_qa_repo }}"
    dest: "{{ koha_qa_dir }}"
    version: "{{ koha_qa_version }}"
    accept_hostkey: yes

- name: Koha QA tools | Set perlcritic for {{ user }}
  file:
    src: "{{ koha_qa_dir }}/perlcriticrc"
    dest: "{{ home_dir }}/.perlcriticrc"
    state: link

- name: Koha QA tools | Set perlcritic for the instance user
  file:
    src: "{{ koha_qa_dir }}/perlcriticrc"
    dest: "/var/lib/koha/{{ koha_instance_name }}/.perlcriticrc"
    mode: 0644
    owner: "{{ koha_instance_name }}-koha"
    state: link
  become: yes
