  - name: Tools | Install default tools
    apt:
      name: "{{ item }}"
      state: latest
      force: yes
    with_items:
      - apt-transport-https
      - bash-completion
      - cpanminus
      - dh-make-perl
      - git
      - git-email
      - apache2
      - libapache2-mpm-itk
      - libdata-printer-perl
      - mlocate
      - perltidy
      - pmtools
      - memcached
      - ntp

  - name: Tools | Install extra tools
    apt:
      name: "{{ extra_tools }}"
      state: latest

  - name: Tools | Install sphinx
    apt:
      name: "{{ item }}"
      state: latest
      force: yes
    with_items:
      - python-sphinx
    when: enable_kohadocs

  - name: Tools | Stop memcached if required
    service:
      name: memcached
      state: started
      enabled: yes
    when: enable_memcached
