# file: roles/kohadevbox/meta/main.yml
---
galaxy_info:
  author: Magnus Enger and Tom√°s Cohen Arazi
  license: GPLv3
  min_ansible_version: 1.6
  platforms:
    - name: Ubuntu
      versions:
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  categories:
     - web
dependencies: []
